replicaCount: 1

image:
  repository: nextjsdemoproject.azurecr.io/demo-test
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  hosts:
    - host: nextjs-app.akshit.tech
      paths:
        - path: /
          pathType: Prefix
  tls: []

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
